codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no


coverage:
  status:
    project:
      target: auto
      threshold: 0%
      if_ci_failed: success
      informational: true
      only_pulls: true
    patch:
      target: auto
      threshold: 0%
      if_ci_failed: success
      informational: true
      only_pulls: true
