name: jlab_segmentation
channels:
  - conda-forge
  - defaults
dependencies:
  - ipympl=0.7.0
  - jupyterlab=3.0.16
  - pip=21.1.1
  - ffmpeg=4.2.2
  - imageio=2.9.0
  - pip:
    - voila==0.2.10
    - git+https://github.com/AllenInstitute/ophys_etl_pipelines@notebook_update
