"""Well known file types"""
from enum import Enum


class WellKnownFileType(Enum):
    # motion correction
    MAX_INTENSITY_PROJECTION_IMAGE = 'MAX_INTENSITY_PROJECTION_IMAGE'
    AVG_INTENSITY_PROJECTION_IMAGE = 'AVG_INTENSITY_PROJECTION_IMAGE'
    REGISTRATION_SUMMARY_IMAGE = 'REGISTRATION_SUMMARY_IMAGE'
    MOTION_CORRECTED_IMAGE_STACK = 'MOTION_CORRECTED_IMAGE_STACK'
    MOTION_X_Y_OFFSET_DATA = 'MOTION_X_Y_OFFSET_DATA'
    MOTION_PREVIEW = 'MOTION_PREVIEW'

    # denoising
    DEEPINTERPOLATION_FINETUNED_MODEL = 'DEEPINTERPOLATION_FINETUNED_MODEL'
    DEEPINTERPOLATION_DENOISED_MOVIE = 'DEEPINTERPOLATION_DENOISED_MOVIE'

    # segmentation
    OPHYS_ROIS = 'OPHYS_ROIS'
