"""workflow steps"""
from enum import Enum


class WorkflowStepEnum(Enum):
    MOTION_CORRECTION = "MOTION_CORRECTION"
    DENOISING_FINETUNING = "DENOISING_FINETUNING"
    DENOISING_INFERENCE = "DENOISING_INFERENCE"
    SEGMENTATION = "SEGMENTATION"
    TRACE_EXTRACTION = "TRACE_EXTRACTION"
    ROI_CLASSIFICATION_GENERATE_CORRELATION_PROJECTION_GRAPH = (
        "ROI_CLASSIFICATION_GENERATE_CORRELATION_PROJECTION_GRAPH"
    )
    ROI_CLASSIFICATION_GENERATE_THUMBNAILS = (
        "ROI_CLASSIFICATION_GENERATE_THUMBNAILS"
    )
    ROI_CLASSIFICATION_CREATE_TRAIN_TEST_SPLIT = (
        "ROI_CLASSIFICATION_CREATE_TRAIN_TEST_SPLIT"
    )
    ROI_CLASSIFICATION_TRAINING = "ROI_CLASSIFICATION_TRAINING"
    ROI_CLASSIFICATION_INFERENCE = "ROI_CLASSIFICATION_INFERENCE"
