"""workflow steps"""
from enum import Enum


class WorkflowStep(Enum):
    MOTION_CORRECTION = 'MOTION_CORRECTION'
    DENOISING_FINETUNING = 'DENOISING_FINETUNING'
    DENOISING_INFERENCE = 'DENOISING_INFERENCE'
    SEGMENTATION = 'SEGMENTATION'
    ROI_CLASSIFICATION_GENERATE_CORRELATION_PROJECTION_GRAPH = \
        'ROI_CLASSIFICATION_GENERATE_CORRELATION_PROJECTION_GRAPH'
    ROI_CLASSIFICATION_GENERATE_THUMBNAILS = \
        'ROI_CLASSIFICATION_GENERATE_THUMBNAILS'
